name: tests-enabled-workflow
on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Prepare dirs
        run: |
          set -euo pipefail
          mkdir -p bin lib test-results

      - name: Fetch JUnit Console (standalone)
        run: |
          set -euo pipefail
          JUNIT_VERSION=1.13.4
          curl -fsSL -o "lib/junit-platform-console-standalone-${JUNIT_VERSION}.jar" \
            "https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/${JUNIT_VERSION}/junit-platform-console-standalone-${JUNIT_VERSION}.jar"

      - name: Compile all Java sources (layout-agnostic)
        run: |
          set -euo pipefail
          JUNIT_JAR=$(echo lib/junit-platform-console-standalone-*.jar)
          # Collect every .java file except under ./bin or ./lib
          find . \
            -path ./bin -prune -o \
            -path ./lib -prune -o \
            -type f -name '*.java' -print > sources.txt

          if [ ! -s sources.txt ]; then
            echo "No .java sources found. Check your repo structure." >&2
            exit 1
          fi

          # Compile everything in one go; JUnit on classpath lets tests compile
          javac -cp "$JUNIT_JAR" -d bin @sources.txt

      - name: Run JUnit tests (scan classpath)
        run: |
          set -euo pipefail
          JUNIT_JAR=$(echo lib/junit-platform-console-standalone-*.jar)
          # Scan compiled classes for tests; fail if none detected
          java -jar "$JUNIT_JAR" \
            --class-path "bin" \
            --scan-class-path \
            --fail-if-no-tests \
            --reports-dir test-results

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: test-results

      - name: Debug (what did CI see?)
        if: failure()
        run: |
          echo "Workspace tree (top-level):"
          ls -la
          echo
          echo "Found sources:"
          sed -n '1,200p' sources.txt || true
