name: tests-enabled-workflow.yml
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Specify the runner environment

    steps:
      - uses: actions/checkout@v4 # Checkout the repository code

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Specify the Java version
          distribution: 'temurin' # Choose a JDK distribution

      - name: Build and Test with Maven
        run: mvn clean install # Compile and run JUnit tests using Maven